---
# Workflow name
name: module3_task2
# action who declench workflow
"on":
  push:
    branches:
      - main
  # programmate time of workflow execution
  schedule:
    - cron: '0 0 * * *'

# all action in this workflow
jobs:
  builds:
    # name of job
    name: up-to-date installation system
    # env of execution
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: installation Hugo with script
        run: cd module3_task2 && ./setup.sh

      - name: Validate Makefile execution make build command
        run: |
          make help
          make build
          make run
          make stop
          make clean
        working-directory: module3_task2

      - name: packaging
        run: make package
      
      - name: archieve ZIP file artifact only if all tests and validation have run successfully
        if: ${{ github.ref == 'refs/heads/main' }} || ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v3
        with:
          name: Saving the zip file
          path: |
            module3_task2/awesome-website.zip
