---
# Workflow name
name: module3_task0
# action who declench workflow
"on":
  push:
    branches:
      - main
  # programmate time of workflow execution
  schedule:
    - cron: '0 0 * * *'

# all action in this workflow
jobs:
  builds:
    # name of job
    name: up-to-date installation system
    # env of execution
    runs-on: ubuntu 22.04

    steps:
      - uses: actions/checkout@v3
      - name: installation Hugo with script
      - run: cd module3_task1 && ./setup.sh
      - name: Validate Makefile execution make build command
        run: |
          make help
          make build
          make run
          make stopcd
          make clean
        working-directory: module3_task1
